import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { изолировать, подготовить, вишУжеВиден } from './stub.mjs';
const К='/Users/naboy/Documents/GitHub/aintonx.github.io';
const srv=createServer(async(q,r)=>{const u=decodeURIComponent(q.url.split('?')[0]);
 try{const b=await readFile(path.join(К,u==='/'?'index.html':u.slice(1)));
 r.writeHead(200,{'Content-Type':u.endsWith('.css')?'text/css':u.endsWith('.js')?'text/javascript':'text/html','Cache-Control':'no-store'});r.end(b);}catch{r.writeHead(404).end();}});
await new Promise(r=>srv.listen(0,'127.0.0.1',r));
const база=`http://127.0.0.1:${srv.address().port}/`;
const br=await chromium.launch();
const ctx=await br.newContext({viewport:{width:390,height:900},colorScheme:'dark'});
const page=await ctx.newPage();
await изолировать(page,база); await вишУжеВиден(page);
await page.goto(база,{waitUntil:'load'}); await подготовить(page);
await page.waitForTimeout(1200);
await page.locator('#condScreen').screenshot({path:process.argv[2]});
console.log('снято');
await br.close(); srv.close();
